/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import ConexionSingleton.Conexion;
import Diagrama.Domicilio;
import Diagrama.ListadoTipoLocalidad;
import Diagrama.ListadoTipoMunicipio;
import Diagrama.ListadoTipoVivienda;
import Diagrama.Localidad;
import Diagrama.Metodos;
import Diagrama.Municipio;
import Diagrama.tipoVivienda;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.*;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;


/**
 *
 * @author User
 */
public class NuevoRegistro extends javax.swing.JFrame {
        
    Conexion conectar = Conexion.getInstace();
    Connection con = conectar.conectar();

    /**
     * Creates new form NuevoRegistro
     */
    public NuevoRegistro() {
        initComponents();
        cargarCombo(cbTipoVivienda);
        cargarComoMunicipio(cbMunicipio);
        //cargarComoLocalidad(cbLocalidad);  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtCalle = new javax.swing.JTextField();
        txtColonia = new javax.swing.JTextField();
        txtCodigoPostal = new javax.swing.JTextField();
        txtEstado = new javax.swing.JTextField();
        cbTipoVivienda = new javax.swing.JComboBox<>();
        cbLocalidad = new javax.swing.JComboBox<>();
        btnAgregarHabitantes = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        cbMunicipio = new javax.swing.JComboBox<>();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Registro Vivienda");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Calle Y Numero:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Colonia:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Codigo Postal:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Municipio:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Estado:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Tipo De Vivienda:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Localidad");

        cbLocalidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbLocalidadMouseClicked(evt);
            }
        });

        btnAgregarHabitantes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/NuevoHabitante.png"))); // NOI18N
        btnAgregarHabitantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarHabitantesMouseClicked(evt);
            }
        });
        btnAgregarHabitantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarHabitantesActionPerformed(evt);
            }
        });

        jLabel9.setText("Agregar habitantes");

        cbMunicipio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbMunicipioItemStateChanged(evt);
            }
        });
        cbMunicipio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMunicipioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnAgregarHabitantes)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(cbTipoVivienda, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(cbLocalidad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(cbMunicipio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(txtCodigoPostal))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(txtColonia))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtCalle, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(txtEstado))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(347, 347, 347)
                        .addComponent(jLabel9)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtCalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(txtColonia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4))
                    .addComponent(txtCodigoPostal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(cbLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cbTipoVivienda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAgregarHabitantes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarHabitantesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarHabitantesMouseClicked
        Metodos met = new Metodos();
        Municipio municipio = new Municipio();
        tipoVivienda vivienda = new tipoVivienda();
        Domicilio domicilio = new Domicilio();
        Localidad localidad = new Localidad();
        
        domicilio.setCalleNumero(txtCalle.getText());
        domicilio.setColonia(txtColonia.getText());
        domicilio.setCodigoPostal(Integer.parseInt(txtCodigoPostal.getText()));
        municipio.setMunicipio(cbMunicipio.getSelectedItem().toString());
        domicilio.setMunicipio(municipio);
        domicilio.setEstado(txtEstado.getText());
        vivienda.setVivienda(cbTipoVivienda.getSelectedItem().toString());
        domicilio.setVivienda(vivienda);
        localidad.setLocalidad(cbLocalidad.getSelectedItem().toString());
        domicilio.setLocalidad(localidad);
        domicilio.registrarDomicilio();

        limpiar();
        
       RegistroHabitante rh = new RegistroHabitante(met.getIdDomicilio());
       rh.setVisible(true);
       dispose();
    }//GEN-LAST:event_btnAgregarHabitantesMouseClicked

    private void btnAgregarHabitantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarHabitantesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarHabitantesActionPerformed

    private void cbMunicipioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMunicipioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMunicipioActionPerformed

    private void cbMunicipioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbMunicipioItemStateChanged
        
    }//GEN-LAST:event_cbMunicipioItemStateChanged

    private void cbLocalidadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbLocalidadMouseClicked
        
    }//GEN-LAST:event_cbLocalidadMouseClicked



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarHabitantes;
    public javax.swing.JComboBox<String> cbLocalidad;
    private javax.swing.JComboBox<String> cbMunicipio;
    public javax.swing.JComboBox<String> cbTipoVivienda;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JTextField txtCalle;
    public javax.swing.JTextField txtCodigoPostal;
    public javax.swing.JTextField txtColonia;
    public javax.swing.JTextField txtEstado;
    // End of variables declaration//GEN-END:variables

    private void cargarCombo(JComboBox c) {
       DefaultComboBoxModel combo = new DefaultComboBoxModel();
       c.setModel(combo);
       ListadoTipoVivienda ltv = new ListadoTipoVivienda();
       
       try{
           Statement st = con.createStatement();
           ResultSet rs = st.executeQuery("select tipoVivienda from dbo.tipoVivienda");
           while(rs.next()){
               tipoVivienda tv = new tipoVivienda();
               tv.setVivienda(rs.getString(1));
               ltv.AgregarTipoVivienda(tv);
               combo.addElement(tv.getVivienda());
           }
       
       }catch(Exception e){
           System.out.println("No se puede mostrar combo box" + e);
       }
    }

    private void cargarComoMunicipio(JComboBox c) {
       DefaultComboBoxModel combo = new DefaultComboBoxModel();
       c.setModel(combo);
       ListadoTipoMunicipio ltm = new ListadoTipoMunicipio();
       try {
           Statement st = con.createStatement();
           ResultSet rs = st.executeQuery("select municipio from dbo.Municipio");
           while(rs.next()){
               Municipio mu = new Municipio();
               mu.setMunicipio(rs.getString(1));
               ltm.AgregarTipoMunicipio(mu);
               combo.addElement(mu.getMunicipio());
           }  
       }catch(SQLException e){
           System.out.println("No se puede mostrar combo box "+ e.toString());
       }
       
       c.addActionListener(new ActionListener() {
           @Override
           public void actionPerformed(ActionEvent e) {
               System.out.println(c.getSelectedItem());
               cargarComoLocalidad(cbLocalidad);  
           }
       });
        
    }
   
    private void cargarComoLocalidad(JComboBox c) {
       DefaultComboBoxModel combo = new DefaultComboBoxModel();
       c.setModel(combo);
       ListadoTipoLocalidad ltl = new ListadoTipoLocalidad();
       Municipio mun = new Municipio();
       mun.setMunicipio(cbMunicipio.getSelectedItem().toString());
       
       try {
           Statement st = con.createStatement();
           ResultSet rs = st.executeQuery("select Localidad from dbo.Localidad where idMunicipio = " + mun.getIdMunicipio());
           while(rs.next()){
               Localidad loc = new Localidad();
               loc.setLocalidad(rs.getString(1));
               ltl.AgregarTipoLocalidad(loc);
               combo.addElement(loc.getLocalidad());
           }  
       }catch(SQLException e){
           System.out.println("No se puede mostrar combo box "+ e.toString());
       }
        
    }
    
    
    
    
    private void limpiar () {
        txtCalle.setText("");
        txtColonia.setText("");
        txtCodigoPostal.setText("");
        txtEstado.setText("");
    }
}
